# Instruction to build libHaru from internal package source
INCLUDE(ExternalProject)
SET(EXTRA "")
IF(APPLE)
   SET(EXTRA  -DCMAKE_INSTALL_NAME_DIR=${CMAKE_INSTALL_PREFIX}/lib)
ENDIF(APPLE)

IF(NOT STANDALONE)
  SET(EXTRA ${EXTRA} -DBUILD_SHARED_LIBS=ON)
ENDIF(NOT STANDALONE) 

EXTERNALPROJECT_ADD(libPCRE
		URL https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.bz2 
		PREFIX ${EXTERNAL_INSTALL_LOCATION}/libPCRE
		CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/libPCRE
			   -DPCRE_BUILD_TESTS=OFF
			   -DPCRE_BUILD_PCREGREP=OFF
			   -DPCRE_BUILD_PCRECPP=OFF
			   ${EXTRA}
		INSTALL_COMMAND ""
		PATCH_COMMAND ${PATCH_EXECUTABLE} -p0 < ${CMAKE_CURRENT_SOURCE_DIR}/Patches/libPCRE_cmake
		)

ExternalProject_Get_Property(libPCRE install_dir)
include_directories(BEFORE SYSTEM ${EXTERNAL_INSTALL_LOCATION}/libPCRE/src/libPCRE-build/)

MESSAGE( STATUS "libPCRE will be built in ${install_dir}" )

#SET( PCRE_LIBRARY_DIRS ${CMAKE_CURRENT_BINARY_DIR}/libHDF5/lib PATH)
# Set uncached variables as per standard.
# 	  set(hdf5_FOUND ON)
SET(PCRE_INCLUDE_DIR "${EXTERNAL_INSTALL_LOCATION}/libPCRE/src/libPCRE-build" CACHE PATH "PCRE include directory" FORCE)

IF(STANDALONE)
  SET(PCRE_LIBRARY ${EXTERNAL_INSTALL_LOCATION}/libPCRE/src/libPCRE-build/libpcre${CMAKE_STATIC_LIBRARY_SUFFIX})
ELSE(STANDALONE)
  SET(PCRE_LIBRARY ${EXTERNAL_INSTALL_LOCATION}/libPCRE/src/libPCRE-build/libpcre${CMAKE_SHARED_LIBRARY_SUFFIX})
  INSTALL(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/libPCRE/lib 
          DESTINATION lib
          USE_SOURCE_PERMISSIONS
					FILES_MATCHING PATTERN "*${CMAKE_SHARED_LIBRARY_SUFFIX}*"
	)
ENDIF(STANDALONE)

